on:
  push:
    branches:
      - master

name: Install, Build, and Deploy
jobs:
  build:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15"
      - name: Install Yarn
        run: npm install -g yarn
      - name: Build
        run: yarn install --frozen-lockfile && yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
